name = "script"
start = 6

[item]
{1,"name","name.bmp"},
{2,"name","name.bmp"},
{3,"name","name.bmp"},
{4,"name","name.bmp"}

[6]
title = "出生"
text = "選擇出生，幫他取個名字"
option = {7, 8, 9}
item = {1,-1,-1}
get_item = {2,3}

[7]
title = "富裕"
text = "一歲抓周，想抓什麼"
option = {10, 11, 12}

[8]
title = "清寒"
text = "你出生於一個農家，家裡透過微薄的收入免強過活，你到了適合上學的年紀了，請選擇："
option = {28, 29, 30}

[9]
title = "孤兒"
text = "自有印象以來，你在孤兒院長大。今天有個人來認養你，你選擇："
option = {34, 35, 36}

[10]
title = "21st century c language"
text = "爸爸看了很高興，覺得你一定是位很有才華的孩子，決定送你去普通小學讀書，希望你能在普通的環境中達到卓越的成績，但當你進到普通小學讀書後被 +9 同學揍，你會怎麼做？"
option = {13, 14, 15}

[11]
title = "清明上河圖"
text = "爸爸看到你選這東西感覺你沒什麼用，不想浪費時間栽培你，所以把你送到少林寺裡面練武功，看看能不能練出個東西，在少林寺裡你看到師父把武功密集藏在床底下，你的選擇是？"
option = {16, 17, 18}

[12]
title = "一千萬存摺"
text = "爸爸看了很高興，覺得這個兒子很有品味，所以決定送兒子去讀貴族學校，在貴族學校你被校霸霸凌，請選擇以下方式反擊"
option = {19, 20, 21}

[13]
title = "抄起球棒跟它輸贏"
text = "你成功打贏，你成為學校裡的大哥，身旁有許多小弟，你加入了幫派，懶覺硬梆幫，上了國中你發現這樣下去會辜負父親對自己的期望，因此決定？"
option = {22, 23, 24}

[14]
title = "給它錢求它不要欺負你"
text = "你真是一個慫包，你父親看你這個樣子覺得你太沒出息了，為了證明給你父親看，證明自己，你決定？"
option = {22, 23, 24}

[15]
title = "直接秀一個閃電五連鞭嚇走它"
text = "校霸被你的絕招嚇到了，所以馬上離開，你也在學校打響名號，人稱馬國寶，你父親知道這件事之後覺得你是小丑，你為了讓父親不要對你感到失望，你決定？"
option = {22, 24, 25}

[16]
title = "偷偷把密集拿走，躲起來偷偷練"
text = "你找個地方好好修行，經過 1 年之後你決定？"
option = {24, 25, 26}

[17]
title = "裝作沒看到，繼續在少林寺當打雜"
text = "你爸看到你進了少林寺還這麼沒出息，一定一輩子撿角，在家人面前數落你，見狀你憤而？"
option = {22, 23, 24}

[18]
title = " 將這件事告訴師兄，和師兄一起另起爐灶"
text = "小小年紀的你，所向無敵，神秘超能力，你和師兄練了一年後發現練功沒辦法當飯吃，你為了讓你父親看的起你，你就？"
option = {22, 23, 24}

[19]
title = " 用超派鐵拳打爆校霸的頭"
text = "爸爸看到你這麼派，覺得你超勇的，非常喜歡你，你為了讓父親對你更刮目相看，你決定？"
option = {22, 23, 24}

[20]
title = " 拿起月旦簡明六法跟校霸講道理"
text = "爸爸看了覺得你很理性，覺得投資在你身上有價值，你為了讓父親對你更刮目相看，你決定？"
option = {22, 24, 27}

[21]
title = " 去找老師求助"
text = "爸爸覺得你很懦弱，什麼事情都要老師處理，你為了讓你父親看的起你，你就？"
option = {22, 23, 24}

[22]
title = "認真讀書，目標考上師大附中"
text = "end."
option = {0,0,0}

[23]
title = "決定變成流氓，成立該地區最大的幫派"
text = "end."
option = {0,0,0}

[24]
title = "決定拿父親的錢去創業"
text = "end."
option = {0,0,0}

[25]
title = "決定成立自己的門派，發明自己的拳法，成為當地超強的武功師父"
text = "end."
option = {0,0,0}

[26]
title = "放棄繼續修行，決定重學校，帶著帥氣的武功，迷倒全校同學，同時目標考上師大附中。"
text = "end."
option = {0,0,0}

[27]
title = "決定競選學生會會長"
text = "end."
option = {0,0,0}

[28]
title = "去上學"
text = "你決定去學了，但由於你家裡窮，用的東西都比較舊，許多同學都霸凌你，嘲笑你，你選擇？"
option = {31,32,33}

[29]
title = "幫家裡種田"
text = "本來一切順利，你們雖然貧困但著簡單快樂的生活，可惜一場颱風改變了這一切，你家田裡的東西全部被吹毀了，你該怎麼辦？"
option = {28,40,41}

[30]
title = "去少林寺練功"
text = "你到了少林寺，在那裡你過得很順利，但某次你打掃師傅的房間時，你看到了師傅的武功秘笈就藏在床底下，你決定？"
option = {47,48,49}

[31]
title = "忍氣吞聲，讀自己的書"
text = "你的認真校花都看在眼裡，他喜歡上了認真的你，跟你告白，你選擇？"
option = {42,43,44}

[32]
title = "該死的混蛋，揍他們一頓"
text = "結果對方人多，你被打的很淒慘，你決定？"
option = {30,31,33}

[33]
title = "跟學校老師告狀"
text = "遊戲結束，老師只覺得是你的錯，把你退學了。"
option = {0,0,0}

[34]
title = "接受認養"
text = "你接受了他的認養，他自稱是一個貴族，能讓你吃好睡好。你從此不愁吃穿，也開始有自己的想法，你想要："
option = {37,38,39}

[35]
title = "假意接受，逃離孤兒院"
text = "之後要去哪?"
option = {38,52,0}

[36]
title = "拒絕，繼續待在孤兒院"
text = "你到了該去學校上課的年紀了，在學校你被霸凌，你選擇"
option = {31,32,33}

[37]
title = "去上學"
text = "在學校，你被校霸霸凌，你選擇"
option = {19,20,21}

[38]
title = "尋找自己親生父母"
text = "你踏上尋找親生父母的旅程"
option = {0,0,0}

[39]
title = "出去闖天下"
text = "要去哪?"
option = {38,53,0}

[40]
title = "捲土重來，重整家園"
text = "遊戲結束，你發現你家土下其實埋有大量寶藏，你成功翻轉人生。"
option = {0,0,0}

[41]
title = "不知道該怎麼辦，在家耍廢"
text = "你突然覺得自己有點太廢，你決定？"
option = {28,45,46}

[42]
title = "仍不理會，繼續苦讀"
text = "遊戲結束，恭喜你有著堅強的意志力，你考上了頂大，賺了大錢，翻轉了人生。"
option = {0,0,0}

[43]
title = "答應告白，跟校花出去玩"
text = "遊戲結束，你跟校花交往，但你太窮了，買不起禮物送他，你被拋棄了，課業也荒廢了，哭哭。"
option = {0,0,0}

[44]
title = "你其實喜歡男生"
text = "遊戲結束，你是甲"
option = {0,0,0}

[45]
title = "借錢去買加密貨幣"
text = "遊戲結束，你時機看得很準，幣值翻了好幾萬倍，恭喜你成功翻轉人生"
option = {0,0,0}

[46]
title = "去夜店打工"
text = "在那裡，你雖然賺很多，但有一次，男同事邀請你一起吸毒，你要回他？"
option = {50,51,44}

[47]
title = "假裝沒看到，繼續練功"
text = "遊戲結束，可惜你天份不夠，師傅把你逐出了少林寺。"
option = {0,0,0}

[48]
title = "偷走秘籍，練取神功"
text = "遊戲結束，你成功練到成了神功，雖然師傅發現了，但他根本打不過你，你也把之前的恩怨都了結了"
option = {0,0,0}

[49]
title = "告訴師兄們"
text = "遊戲結束，你的師兄們跟師父告狀，你被師傅逐出少林寺..."
option = {0,0,0}

[50]
title = "當然一起抽啊"
text = "遊戲結束，你抽了之後發現毒品超噁心，你就離職了，把賺到的錢拿回去孝敬父母，你真棒"
option = {0,0,0}

[51]
title = "吸毒不好"
text = "遊戲結束，你同事覺得你是國小屁孩，不爽揍你一頓，你被打到鼻青臉腫，送醫不治..."
option = {0,0,0}

[52]
title = "在街頭流浪"
text = "你從此露宿街頭..."
option = {0,0,0}