script="成為皇帝" 
start=1 // 定義劇本的開始節點 

[item] 
{1,"龍紋玉佩","pic1.bmp"} 
{2,"智者之書","pic2.bmp"} 
{3,"寶劍","pic3.bmp"} 

[player]
stat.name="luck"
stat=5
state=50 // 初始狀態

[npc]
{1,"智者","pic1.bmp","NULL",0}
{2,"俠客","pic2.bmp",NULL,0}
{3,"宮女間諜","pic3.bmp",NULL,0}
{4,"陰險宦官","pic4.bmp",NULL,0}

[1]
title="出生"
background="皇宮" 
text="請選擇出生的條件 並幫他取個名字請選擇出生的條件 並幫他取個名字請選擇出生的條件 並幫他取個名字請選擇出生的條件 並幫他取個名字請選擇出生的條件 並幫他取個名字"
option={2,3,4} 

[2]
title="皇子"
text="你出生在皇宮，是皇上最小的兒子，你接下來的選擇你出生在皇宮，是皇上最小的兒子，你接下來的選擇你出生在皇宮，是皇上最小的兒子，你接下來的選擇你出生在皇宮，是皇上最小的兒子，你接下來的選擇"
option={5,6,7} 
player.state=50

[3]
title="書生"
background="書院" 
text="你出生在書香門第，憑藉自己的努力成為了書生，你接下來的選擇"
option={8,9,10} 
player.state=50

[4]
title="賤民"
background="茅舍" 
text="你出生於賤民之家，生活窮困，你接下來的選擇"
option={11,12,13} 
player.state=50

// 共同劇情節點：發現陰謀
[5]
title="宮廷生活"
background="宮廷"
text="你在宮廷中發現了一個驚天陰謀。"
option={14,15,16}
player.state=50

[6]
title="皇子的冒險"
background="宮廷"
text="你決定展開一場冒險，了解更多宮廷中的秘密。"
option={17,18,19}
player.state=50

[7]
title="皇子的學習"
background="書房"
text="你在書房中學習，了解了更多關於朝政的知識。"
option={14,15,16}
player.state=50

[8]
title="進士之路"
background="書院"
text="你在朝廷中發現了一個驚天陰謀。"
option={14,15,16}
player.state=50

[9]
title="書生的冒險"
background="書院"
text="你決定展開一場冒險，了解更多朝廷中的秘密。"
option={17,18,19}
player.state=50

[10]
title="書生的學習"
background="書房"
text="你在書房中學習，了解了更多關於朝政的知識。"
option={14,15,16}
player.state=50

[11]
title="市井生涯"
background="市井"
text="你在市井中聽聞了一個驚天陰謀。"
option={14,15,16}
player.state=50

[12]
title="賤民的冒險"
background="市井"
text="你決定展開一場冒險，了解更多宮廷中的秘密。"
option={17,18,19}
player.state=50

[13]
title="賤民的學習"
background="茅舍"
text="你在茅舍中學習，了解了更多關於宮廷的知識。"
option={14,15,16}
player.state=50

[14]
title="尋求智者的建議"
background="宮廷"
text="智者提供了你一些有用的建議。"
option={20,21,22}
player.state=60
npc=1

[15]
title="尋求俠客的保護"
background="宮廷"
text="俠客承諾保護你並幫助你收集情報。"
option={20,21,22}
player.state=60
npc=2

[16]
title="尋找宮女間諜的情報"
background="宮廷"
text="宮女間諜告訴你一些關鍵的情報。"
option={20,21,22}
player.state=60
npc=3

[17]
title="宮廷中的隱秘通道"
background="宮廷"
text="你發現了一條宮廷中的隱秘通道，這裡藏著一些秘密。"
option={14,15,16}
player.state=55

[18]
title="朝廷中的密謀"
background="朝堂"
text="你聽到了一些朝廷中的密謀，這些信息對你很重要。"
option={14,15,16}
player.state=55

[19]
title="宮廷花園的秘密"
background="花園"
text="你在宮廷花園中發現了一些秘密。"
option={14,15,16}
player.state=55

[20]
title="面臨挑戰"
background="宮廷"
text="你在揭露陰謀時遭遇了陰險宦官的反擊。"
option={23,24,25}
player.state=50
npc=4

[21]
title="智者的進一步建議"
background="宮廷"
text="智者給了你一些進一步的建議。"
option={23,24,25}
player.state=70
npc=1

[22]
title="俠客的進一步幫助"
background="宮廷"
text="俠客給了你一些進一步的幫助。"
option={23,24,25}
player.state=70
npc=2

[23]
title="成功獲得龍紋玉佩"
background="宮廷"
text="你成功面對挑戰，獲得了龍紋玉佩。"
option={26,27,28}
player.state=80
player.inventory.add=1

[24]
title="成功獲得智者之書"
background="宮廷"
text="你成功面對挑戰，獲得了智者之書。"
option={26,27,28}
player.state=80
player.inventory.add=2

[25]
title="成功獲得寶劍"
background="宮廷"
text="你成功面對挑戰，獲得了寶劍。"
option={26,27,28}
player.state=80
player.inventory.add=3

[26]
title="最後的決戰"
background="皇宮"
text="你面臨最後的決戰，成敗在此一舉。"
to={1:35, -1:30} // 如果擁有龍紋玉佩跳到35，否則跳到30
player.state=90

[27]
title="最後的策略"
background="皇宮"
text="你使用了最後的策略，準備迎接挑戰。"
to={2:36, -1:30} // 如果擁有智者之書跳到36，否則跳到30
player.state=90

[28]
title="最後的對決"
background="皇宮"
text="你與敵人展開了最後的對決，結果即將揭曉。"
to={3:37, -1:30} // 如果擁有寶劍跳到37，否則跳到30
player.state=90

[29]
title="成功當上皇帝"
background="皇宮"
text="你最終成功揭發了陰謀，登上了皇位。"
option={0,0,0}
player.state=100

[30]
title="失敗"
background="皇宮"
text="你未能成功揭發陰謀，失去了繼承權。"
option={0,0,0}
player.state=0

[31]
title="另類成功"
background="皇宮"
text="雖然你未能成為皇帝，但你找到了自己的道路，成為了一位有名的俠士。"
option={0,0,0}
player.state=50

[32]
title="策略與決策"
background="皇宮"
text="你決定如何應對最終的挑戰，選擇了第一個策略。"
option={38,39,40}
player.state=95

[33]
title="決戰計劃"
background="皇宮"
text="你決定如何應對最終的挑戰，選擇了第二個計劃。"
option={41,42,43}
player.state=95

[34]
title="臨場應變"
background="皇宮"
text="你決定如何應對最終的挑戰，選擇了臨場應變。"
option={44,45,46}
player.state=95

[35]
title="使用龍紋玉佩"
background="皇宮"
text="你使用了龍紋玉佩，成功應對了挑戰，登上了皇位。"
option={0,0,0}
player.state=100

[36]
title="使用智者之書"
background="皇宮"
text="你使用了智者之書，成功制定了一個巧妙的策略，擊敗了敵人。"
option={0,0,0}
player.state=100

[37]
title="使用寶劍"
background="皇宮"
text="你使用了寶劍，勇敢地面對敵人並最終取得勝利。"
option={0,0,0}
player.state=100

// 中間劇情和物品分發場景

[38]
title="智者的策略"
background="皇宮"
text="你使用了智者提供的策略，準備迎接最終的挑戰。"
option={47,48,49}
player.state=95

[39]
title="智者的預言"
background="皇宮"
text="你根據智者的預言，做出了相應的準備。"
option={47,48,49}
player.state=95

[40]
title="智者的支持"
background="皇宮"
text="智者提供了強有力的支持，讓你更加自信。"
option={47,48,49}
player.state=95

[41]
title="俠客的幫助"
background="皇宮"
text="俠客給予了你強大的支持，讓你能夠應對挑戰。"
option={50,51,52}
player.state=95

[42]
title="俠客的戰略"
background="皇宮"
text="你使用了俠客提供的戰略，準備迎接挑戰。"
option={50,51,52}
player.state=95

[43]
title="俠客的保護"
background="皇宮"
text="俠客親自保護你，讓你能夠專注於挑戰。"
option={50,51,52}
player.state=95

[44]
title="臨場應變策略"
background="皇宮"
text="你根據臨場情況，靈活應變，準備迎接挑戰。"
option={53,54,55}
player.state=95

[45]
title="臨場決策"
background="皇宮"
text="你在挑戰中做出了迅速而果斷的決策。"
option={53,54,55}
player.state=95

[46]
title="臨場變數"
background="皇宮"
text="你根據臨場變數，靈活應對，準備迎接挑戰。"
option={53,54,55}
player.state=95

[47]
title="策略成功"
background="皇宮"
text="你成功運用智者的策略，擊敗了敵人，登上了皇位。"
option={0,0,0}
player.state=100

[48]
title="預言成真"
background="皇宮"
text="智者的預言成真，你成功應對了挑戰，成為了皇帝。"
option={0,0,0}
player.state=100

[49]
title="支持的力量"
background="皇宮"
text="在智者的支持下，你最終取得了勝利，成為了皇帝。"
option={0,0,0}
player.state=100

[50]
title="俠客的勝利"
background="皇宮"
text="俠客的幫助讓你成功擊敗了敵人，登上了皇位。"
option={0,0,0}
player.state=100

[51]
title="戰略成功"
background="皇宮"
text="你成功運用了俠客的戰略，成為了皇帝。"
option={0,0,0}
player.state=100

[52]
title="保護的力量"
background="皇宮"
text="在俠客的保護下，你最終取得了勝利，成為了皇帝。"
option={0,0,0}
player.state=100

[53]
title="應變成功"
background="皇宮"
text="你成功應變，擊敗了敵人，成為了皇帝。"
option={0,0,0}
player.state=100

[54]
title="決策勝利"
background="皇宮"
text="你的臨場決策讓你成功成為了皇帝。"
option={0,0,0}
player.state=100

[55]
title="變數掌控"
background="皇宮"
text="你成功掌控了變數，最終成為了皇帝。"
option={0,0,0}
player.state=100
