name = "宮廷模擬"
start = 1

[1]
title = "皇子誕生"
text = "你是一名皇子，從小在宮中長大。選擇你的教育方向："
option = {2, 3, 4}

[2]
title = "文學教育"
text = "你選擇專注於文學教育，學習儒家經典和詩書禮儀。選擇下一步行動："
option = {5, 6, 7}

[3]
title = "武學教育"
text = "你選擇專注於武學教育，學習劍術和戰略。選擇下一步行動："
option = {8, 9, 10}

[4]
title = "兼修文武"
text = "你選擇兼修文武，既學習儒家經典也鍛煉武術。選擇下一步行動："
option = {11, 12, 13}

[5]
title = "結交文士"
text = "你結交了一些文士朋友，他們給你帶來了很多知識和見聞。選擇下一步行動："
option = {14, 15, 16}

[6]
title = "讀書考試"
text = "你專心讀書，參加宮廷中的考試。選擇下一步行動："
option = {17, 18, 19}

[7]
title = "書寫文章"
text = "你開始書寫文章，向皇帝展示你的才華。選擇下一步行動："
option = {20, 21, 22}

[8]
title = "習練劍術"
text = "你每天早晨都在習練劍術，不斷提升自己的武藝。選擇下一步行動："
option = {23, 24, 25}

[9]
title = "參加狩獵"
text = "你參加了宮中的狩獵活動，展示了你的武藝。選擇下一步行動："
option = {26, 27, 28}

[10]
title = "軍事訓練"
text = "你參加了軍事訓練，學習戰略和戰術。選擇下一步行動："
option = {29, 30, 31}

[11]
title = "訪問學者"
text = "你訪問了宮廷中的學者，學習他們的知識和智慧。選擇下一步行動："
option = {32, 33, 34}

[12]
title = "與將軍交流"
text = "你與宮中的將軍交流，學習戰略和戰術。選擇下一步行動："
option = {35, 36, 37}

[13]
title = "探訪百姓"
text = "你決定探訪百姓，了解他們的生活和需求。選擇下一步行動："
option = {38, 39, 40}

[14]
title = "參加文會"
text = "你參加了一場文會，展示了你的文學才華。選擇下一步行動："
option = {41, 42, 43}

[15]
title = "研究經典"
text = "你開始深入研究儒家經典，提高自己的學問。選擇下一步行動："
option = {44, 45, 46}

[16]
title = "撰寫詩詞"
text = "你撰寫了一首詩詞，贏得了宮廷文人的讚賞。選擇下一步行動："
option = {47, 48, 49}

[17]
title = "科舉高榜"
text = "你在科舉考試中取得了高榜，贏得了皇帝的賞識。選擇下一步行動："
option = {50, 51, 52}

[18]
title = "科舉落榜"
text = "你在科舉考試中落榜，但你並未氣餒。選擇下一步行動："
option = {53, 54, 55}

[19]
title = "專心讀書"
text = "你決定繼續專心讀書，提升自己的學問。選擇下一步行動："
option = {56, 57, 58}

[20]
title = "得到賞識"
text = "你的文章得到了皇帝的賞識，開始進入朝廷為官。選擇下一步行動："
option = {59, 60, 61}

[21]
title = "遭到嫉妒"
text = "你的才華引來了其他人的嫉妒，面臨宮廷鬥爭。選擇下一步行動："
option = {62, 63, 64}

[22]
title = "默默無聞"
text = "你的文章沒有得到重視，你決定默默無聞地繼續努力。選擇下一步行動："
option = {65, 66, 67}

[23]
title = "擊敗對手"
text = "你在一場比武中擊敗了對手，贏得了眾人的讚賞。選擇下一步行動："
option = {68, 69, 70}

[24]
title = "受傷"
text = "你在習練劍術中不慎受傷，需要休養一段時間。選擇下一步行動："
option = {71, 72, 73}

[25]
title = "挑戰將軍"
text = "你決定挑戰宮中的將軍，展示你的實力。選擇下一步行動："
option = {74, 75, 76}

[26]
title = "成功狩獵"
text = "你在狩獵中成功獵獲了一頭猛獸，贏得了大家的讚賞。選擇下一步行動："
option = {77, 78, 79}

[27]
title = "狩獵受傷"
text = "你在狩獵中不慎受傷，需要休養一段時間。選擇下一步行動："
option = {80, 81, 82}

[28]
title = "展示武藝"
text = "你在狩獵中展示了高超的武藝，贏得了眾人的讚賞。選擇下一步行動："
option = {83, 84, 85}

[29]
title = "成為將軍"
text = "你在軍事訓練中表現出色，被任命為一名小將軍。選擇下一步行動："
option = {86, 87, 88}

[30]
title = "戰略制定"
text = "你在軍事訓練中學會了制定戰略，開始參與軍事計劃。選擇下一步行動："
option = {89, 90, 91}

[31]
title = "軍事演習"
text = "你參加了一次軍事演習，展示了你的才能。選擇下一步行動："
option = {92, 93, 94}

[32]
title = "學習禮儀"
text = "你從學者那裡學習了很多禮儀和知識，提升了自己的修養。選擇下一步行動："
option = {95, 96, 97}

[33]
title = "參加文會"
text = "你參加了一次文會，展示了你的才華。選擇下一步行動："
option = {98, 99, 100}

[34]
title = "研究經典"
text = "你跟隨學者一起研究儒家經典，提升了自己的學問。選擇下一步行動："
option = {101, 102, 103}

[35]
title = "學習戰略"
text = "你從將軍那裡學習了很多戰略和戰術，提升了自己的軍事才能。選擇下一步行動："
option = {104, 105, 106}

[36]
title = "參加軍事會議"
text = "你參加了一次軍事會議，展示了你的戰略才能。選擇下一步行動："
option = {107, 108, 109}

[37]
title = "軍事演習"
text = "你參加了一次軍事演習，展示了你的才能。選擇下一步行動："
option = {110, 111, 112}

[38]
title = "訪問百姓"
text = "你訪問了百姓，了解他們的生活和需求。選擇下一步行動："
option = {113, 114, 115}

[39]
title = "捐獻財物"
text = "你決定捐獻一些財物給百姓，贏得了他們的愛戴。選擇下一步行動："
option = {116, 117, 118}

[40]
title = "組織救濟"
text = "你組織了一次救濟活動，幫助了許多貧困的百姓。選擇下一步行動："
option = {119, 120, 121}

[41]
title = "得儒士賞識"
text = "你的才華得到了儒士們的賞識，他們願意支持你。選擇下一步行動："
option = {122, 123, 124}

[42]
title = "受到嫉妒"
text = "你的才華引來了其他人的嫉妒，面臨宮廷鬥爭。選擇下一步行動："
option = {125, 126, 127}

[43]
title = "進一步深造"
text = "你決定進一步深造，提升自己的學問和才華。選擇下一步行動："
option = {128, 129, 130}

[44]
title = "撰寫經典"
text = "你決定撰寫一部經典著作，展示你的學問。選擇下一步行動："
option = {131, 132, 133}

[45]
title = "參加科舉"
text = "你決定參加科舉考試，檢驗自己的學問。選擇下一步行動："
option = {134, 135, 136}

[46]
title = "成為老師"
text = "你決定成為一名老師，教授學生儒家經典。選擇下一步行動："
option = {137, 138, 139}

[47]
title = "被賞識"
text = "你的詩詞得到了皇帝的賞識，開始進入朝廷為官。選擇下一步行動："
option = {140, 141, 142}

[48]
title = "遭到嫉妒"
text = "你的才華引來了其他人的嫉妒，面臨宮廷鬥爭。選擇下一步行動："
option = {143, 144, 145}name = "宮廷模擬"
start = 1

[1]
title = "宮廷生活"
text = "你出生在古代宮廷，選擇你的身份："
option = {2, 3, 4}

[2]
title = "皇子"
text = "你是皇子，選擇你的愛好："
option = {5, 6, 7}

[3]
title = "公主"
text = "你是公主，選擇你的愛好："
option = {8, 9, 10}

[4]
title = "大臣之子"
text = "你是大臣之子，選擇你的愛好："
option = {11, 12, 13}

[5]
title = "學習武藝"
text = "你熱愛武藝，決定進一步深造。選擇："
option = {14, 15, 16}

[6]
title = "學習詩書"
text = "你熱愛詩書，決定進一步學習。選擇："
option = {17, 18, 19}

[7]
title = "愛好狩獵"
text = "你熱愛狩獵，經常外出狩獵。選擇："
option = {20, 21, 22}

[8]
title = "學習琴棋書畫"
text = "你熱愛琴棋書畫，選擇進一步深造："
option = {23, 24, 25}

[9]
title = "學習醫術"
text = "你熱愛醫術，選擇進一步學習："
option = {26, 27, 28}

[10]
title = "愛好舞蹈"
text = "你熱愛舞蹈，經常在宮中表演。選擇："
option = {29, 30, 31}

[11]
title = "學習武藝"
text = "你熱愛武藝，決定進一步深造。選擇："
option = {32, 33, 34}

[12]
title = "學習詩書"
text = "你熱愛詩書，決定進一步學習。選擇："
option = {35, 36, 37}

[13]
title = "愛好商業"
text = "你對商業感興趣，選擇進一步學習："
option = {38, 39, 40}

[14]
title = "參加武試"
text = "你參加了武試，並取得了優異成績。選擇："
option = {41, 42, 43}

[15]
title = "跟隨名師學藝"
text = "你跟隨名師學藝，武藝大進。選擇："
option = {44, 45, 46}

[16]
title = "參加比武大會"
text = "你參加了比武大會，展現了驚人的實力。選擇："
option = {47, 48, 49}

[17]
title = "參加科舉"
text = "你參加了科舉，並取得了進士資格。選擇："
option = {50, 51, 52}

[18]
title = "撰寫經典"
text = "你撰寫了一部經典著作，贏得了名聲。選擇："
option = {53, 54, 55}

[19]
title = "成為老師"
text = "你成為了一名老師，教授學生。選擇："
option = {56, 57, 58}

[20]
title = "參加狩獵比賽"
text = "你參加了狩獵比賽，取得了優勝。選擇："
option = {59, 60, 61}

[21]
title = "外出冒險"
text = "你外出冒險，經歷了許多奇遇。選擇："
option = {62, 63, 64}

[22]
title = "狩獵珍奇異獸"
text = "你決定狩獵珍奇異獸，展現你的勇氣。選擇："
option = {65, 66, 67}

[23]
title = "學習琴藝"
text = "你在琴藝上取得了很大的成就。選擇："
option = {68, 69, 70}

[24]
title = "學習書法"
text = "你在書法上取得了很大的成就。選擇："
option = {71, 72, 73}

[25]
title = "學習繪畫"
text = "你在繪畫上取得了很大的成就。選擇："
option = {74, 75, 76}

[26]
title = "成為宮廷醫師"
text = "你成為了一名宮廷醫師，幫助了很多人。選擇："
option = {77, 78, 79}

[27]
title = "研究藥理"
text = "你深入研究藥理，發現了很多新藥。選擇："
option = {80, 81, 82}

[28]
title = "醫治百姓"
text = "你經常下鄉醫治百姓，贏得了他們的愛戴。選擇："
option = {83, 84, 85}

[29]
title = "參加宮廷表演"
text = "你經常參加宮廷表演，贏得了掌聲。選擇："
option = {86, 87, 88}

[30]
title = "創作舞蹈"
text = "你創作了很多新的舞蹈，得到大家的喜愛。選擇："
option = {89, 90, 91}

[31]
title = "教授舞蹈"
text = "你成為了一名舞蹈老師，教出了很多優秀的學生。選擇："
option = {92, 93, 94}

[32]
title = "參加武試"
text = "你參加了武試，並取得了優異成績。選擇："
option = {95, 96, 97}

[33]
title = "跟隨名師學藝"
text = "你跟隨名師學藝，武藝大進。選擇："
option = {98, 99, 100}

[34]
title = "參加比武大會"
text = "你參加了比武大會，展現了驚人的實力。選擇："
option = {101, 102, 103}

[35]
title = "參加科舉"
text = "你參加了科舉，並取得了進士資格。選擇："
option = {104, 105, 106}

[36]
title = "撰寫經典"
text = "你撰寫了一部經典著作，贏得了名聲。選擇："
option = {107, 108, 109}

[37]
title = "成為老師"
text = "你成為了一名老師，教授學生。選擇："
option = {110, 111, 112}

[38]
title = "經營商號"
text = "你開始經營自己的商號，賺取了不少財富。選擇："
option = {113, 114, 115}

[39]
title = "投資貿易"
text = "你投資了很多貿易，獲得了豐厚的回報。選擇："
option = {116, 117, 118}

[40]
title = "建立商會"
text = "你建立了一個商會，成為了商界的領袖。選擇："
option = {119, 120, 121}

[41]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[42]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[43]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。選擇："
option = {128, 129, 130}

[44]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[45]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[46]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。選擇："
option = {128, 129, 130}

[47]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[48]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[49]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。選擇："
option = {128, 129, 130}

[50]
title = "成為宰相"
text = "你通過科舉，最終成為了宰相。你在朝廷中鞠躬盡瘁，名留青史。"
option = {}

[51]
title = "遭遇挑戰"
text = "你在朝廷中面臨其他官員的挑戰，需要展示你的才能。選擇："
option = {131, 132, 133}

[52]
title = "被罷官"
text = "你因政見不同，被罷官回家，但你決定著書立說，名垂後世。"
option = {}

[53]
title = "成為名儒"
text = "你的著作成為經典，你成為了一代名儒，受人尊敬。"
option = {}

[54]
title = "被人抄襲"
text = "你的著作被人抄襲，你決定追求正義，選擇下一步行動："
option = {134, 135, 136}

[55]
title = "繼續寫作"
text = "你決定繼續寫作，不斷創作出更多經典之作。"
option = {}

[56]
title = "受到學生愛戴"
text = "你成為了一名受人尊敬的老師，桃李滿天下。"
option = {}

[57]
title = "遭遇挑戰"
text = "你在教學中面臨挑戰，需要展示你的學識和能力。選擇："
option = {137, 138, 139}

[58]
title = "被罷免"
text = "你因政見不同，被罷免回家，但你決定著書立說，名垂後世。"
option = {}

[59]
title = "成為狩獵之王"
text = "你在狩獵比賽中多次奪冠，最終成為了狩獵之王。"
option = {}

[60]
title = "遭遇危險"
text = "你在狩獵中遭遇危險，需要迅速應對。選擇："
option = {140, 141, 142}

[61]
title = "受賞賜"
text = "你在狩獵中表現優異，受到了皇帝的賞賜。"
option = {}

[62]
title = "得到寶物"
text = "你在冒險中得到了寶物，決定如何處理它。選擇："
option = {143, 144, 145}

[63]
title = "遭遇危險"
text = "你在冒險中遭遇危險，需要迅速應對。選擇："
option = {146, 147, 148}

[64]
title = "獲得聲譽"
text = "你在冒險中表現優異，獲得了廣泛的聲譽。"
option = {}

[65]
title = "被任命為獵隊長"
text = "你在狩獵中表現出色，被任命為獵隊長。"
option = {}

[66]
title = "遇到神秘人"
text = "你在狩獵中遇到了一個神秘人，選擇如何應對。選擇："
option = {149, 150, 151}

[67]
title = "遭遇危險"
text = "你在狩獵中遭遇危險，需要迅速應對。選擇："
option = {152, 153, 154}


[49]
title = "默默無聞"
text = "你的詩詞沒有得到重視，你決定默默無聞地繼續努力。選擇下一步行動："
option = {146, 147, 148}

[50]
title = "進入朝廷"
text = "你被任命為一名小官，開始參與朝廷事務。選擇下一步行動："
option = {149, 150, 151}

[51]
title = "受到挑戰"
text = "你在朝廷中面臨其他官員的挑戰，需要展示你的才能。選擇下一步行動："
option = {152, 153, 154}

[52]
title = "受到重用"
text = "你的才能得到了皇帝的重用，被任命為重要職位。選擇下一步行動："
option = {155, 156, 157}

[53]
title = "重振旗鼓"
text = "你決定重振旗鼓，繼續努力學習。選擇下一步行動："
option = {158, 159, 160}

[54]
title = "參加武試"
text = "你決定參加武試，展示你的武藝。選擇下一步行動："
option = {161, 162, 163}

[55]
title = "繼續讀書"
text = "你決定繼續讀書，提升自己的學問。選擇下一步行動："
option = {164, 165, 166}

[56]
title = "考上進士"
text = "你在科舉中考上了進士，贏得了皇帝的賞識。選擇下一步行動："
option = {167, 168, 169}

[57]
title = "未能考上"
text = "你在科舉中未能考上，但你決定繼續努力。選擇下一步行動："
option = {170, 171, 172}

[58]
title = "進一步學習"
text = "你決定進一步學習，提升自己的學問。選擇下一步行動："
option = {173, 174, 175}

[59]
title = "被任命官職"
text = "你被任命為一名小官，開始參與朝廷事務。選擇下一步行動："
option = {176, 177, 178}

[60]
title = "受到挑戰"
text = "你在朝廷中面臨其他官員的挑戰，需要展示你的才能。選擇下一步行動："
option = {179, 180, 181}

[61]
title = "受到重用"
text = "你的才能得到了皇帝的重用，被任命為重要職位。選擇下一步行動："
option = {182, 183, 184}

[62]
title = "面對挑戰"
text = "你面對其他官員的挑戰，選擇如何應對："
option = {185, 186, 187}

[63]
title = "結交盟友"
text = "你決定結交一些盟友，共同對抗敵對勢力。選擇下一步行動："
option = {188, 189, 190}

[64]
title = "專注學問"
text = "你決定專注於學問，暫時避開宮廷鬥爭。選擇下一步行動："
option = {191, 192, 193}

[65]
title = "深造學問"
text = "你決定進一步深造，提升自己的學問和才華。選擇下一步行動："
option = {194, 195, 196}

[66]
title = "默默努力"
text = "你決定默默努力，等待合適的機會。選擇下一步行動："
option = {197, 198, 199}

[67]
title = "轉變策略"
text = "你決定轉變策略，尋找其他發展機會。選擇下一步行動："
option = {200, 201, 202}

[68]
title = "成為名將"
text = "你憑藉武藝和智慧，成為了一名名將。選擇下一步行動："
option = {203, 204, 205}

[69]
title = "受到賞識"
text = "你的武藝得到了皇帝的賞識，被任命為一名將軍。選擇下一步行動："
option = {206, 207, 208}

[70]
title = "挑戰更強對手"
text = "你決定挑戰更強的對手，展示你的實力。選擇下一步行動："
option = {209, 210, 211}

[71]
title = "休養生息"
text = "你決定好好休養，恢復健康後再繼續努力。選擇下一步行動："
option = {212, 213, 214}

[72]
title = "求醫治療"
text = "你尋求名醫治療，希望早日康復。選擇下一步行動："
option = {215, 216, 217}

[73]
title = "轉向學問"
text = "你決定暫時放下武學，轉向學問的研究。選擇下一步行動："
option = {218, 219, 220}

[74]
title = "擊敗將軍"
text = "你在比武中擊敗了將軍，贏得了大家的尊敬。選擇下一步行動："
option = {221, 222, 223}

[75]
title = "學習戰術"
text = "你從將軍那裡學習了很多戰術，提升了自己的軍事才能。選擇下一步行動："
option = {224, 225, 226}

[76]
title = "加入軍隊"
text = "你決定加入軍隊，實戰中提升自己的武藝。選擇下一步行動："
option = {227, 228, 229}

[77]
title = "得到獎勵"
text = "你在狩獵中成功，皇帝獎"

[68]
title = "被宮廷音樂家賞識"
text = "你的琴藝得到了宮廷音樂家的賞識，決定邀請你合作創作。選擇："
option = {155, 156, 157}

[69]
title = "進一步深造"
text = "你決定進一步深造琴藝，追求更高的境界。"
option = {}

[70]
title = "成為宮廷音樂家"
text = "你的琴藝卓越，最終成為了一名宮廷音樂家，享譽宮廷。"
option = {}

[71]
title = "被宮廷書法家賞識"
text = "你的書法得到了宮廷書法家的賞識，決定邀請你合作創作。選擇："
option = {158, 159, 160}

[72]
title = "進一步深造"
text = "你決定進一步深造書法，追求更高的境界。"
option = {}

[73]
title = "成為宮廷書法家"
text = "你的書法卓越，最終成為了一名宮廷書法家，享譽宮廷。"
option = {}

[74]
title = "被宮廷畫家賞識"
text = "你的繪畫得到了宮廷畫家的賞識，決定邀請你合作創作。選擇："
option = {161, 162, 163}

[75]
title = "進一步深造"
text = "你決定進一步深造繪畫，追求更高的境界。"
option = {}

[76]
title = "成為宮廷畫家"
text = "你的繪畫卓越，最終成為了一名宮廷畫家，享譽宮廷。"
option = {}

[77]
title = "受皇帝嘉獎"
text = "你作為宮廷醫師，治癒了皇帝的疾病，受到了嘉獎。選擇："
option = {164, 165, 166}

[78]
title = "進一步研究"
text = "你決定進一步研究醫術，尋求更多的突破。"
option = {}

[79]
title = "成為宮廷首席醫師"
text = "你醫術卓越，最終成為了宮廷首席醫師，受人尊敬。"
option = {}

[80]
title = "發現奇藥"
text = "你發現了一種奇藥，決定如何使用它。選擇："
option = {167, 168, 169}

[81]
title = "進一步研究"
text = "你決定進一步研究藥理，追求更多的突破。"
option = {}

[82]
title = "成為藥學大師"
text = "你的藥學研究卓越，最終成為了一名藥學大師，受人尊敬。"
option = {}

[83]
title = "受到百姓愛戴"
text = "你經常下鄉醫治百姓，受到他們的愛戴。"
option = {}

[84]
title = "遇到神秘病人"
text = "你遇到了一個神秘病人，決定如何處理他的病情。選擇："
option = {170, 171, 172}

[85]
title = "建立醫院"
text = "你決定建立一所醫院，為更多的人提供醫療服務。"
option = {}

[86]
title = "被皇帝賞識"
text = "你的舞蹈得到了皇帝的賞識，邀請你參加更多宮廷表演。選擇："
option = {173, 174, 175}

[87]
title = "創作更多舞蹈"
text = "你決定創作更多的舞蹈，追求更高的藝術成就。"
option = {}

[88]
title = "成為宮廷首席舞者"
text = "你的舞蹈卓越，最終成為了一名宮廷首席舞者，享譽宮廷。"
option = {}

[89]
title = "被宮廷舞者賞識"
text = "你的舞蹈創作得到了宮廷舞者的賞識，決定邀請你合作創作。選擇："
option = {176, 177, 178}

[90]
title = "進一步深造"
text = "你決定進一步深造舞蹈，追求更高的藝術成就。"
option = {}

[91]
title = "成為宮廷舞蹈家"
text = "你的舞蹈創作卓越，最終成為了一名宮廷舞蹈家，享譽宮廷。"
option = {}

[92]
title = "受學生愛戴"
text = "你成為了一名受人尊敬的舞蹈老師，桃李滿天下。"
option = {}

[93]
title = "創辦舞蹈學院"
text = "你決定創辦一所舞蹈學院，培養更多的舞蹈人才。"
option = {}

[94]
title = "成為舞蹈名師"
text = "你的教學卓越，最終成為了一名舞蹈名師，受人尊敬。"
option = {}

[95]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[96]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[97]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。"
option = {}

[98]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[99]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[100]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。"
option = {}

[101]
title = "被任命將軍"
text = "你的武藝得到了賞識，被任命為將軍。選擇："
option = {122, 123, 124}

[102]
title = "被嫉妒陷害"
text = "你在宮中遭到嫉妒，被人陷害。選擇："
option = {125, 126, 127}

[103]
title = "繼續深造"
text = "你決定繼續深造，提升自己的武藝。"
option = {}

[104]
title = "成為宰相"
text = "你通過科舉，最終成為了宰相。你在朝廷中鞠躬盡瘁，名留青史。"
option = {}

[105]
title = "遭遇挑戰"
text = "你在朝廷中面臨其他官員的挑戰，需要展示你的才能。選擇："
option = {131, 132, 133}

[106]
title = "被罷官"
text = "你因政見不同，被罷官回家，但你決定著書立說，名垂後世。"
option = {}

[107]
title = "成為名儒"
text = "你的著作成為經典，你成為了一代名儒，受人尊敬。"
option = {}

[108]
title = "被人抄襲"
text = "你的著作被人抄襲，你決定追求正義，選擇下一步行動："
option = {134, 135, 136}

[109]
title = "繼續寫作"
text = "你決定繼續寫作，不斷創作出更多經典之作。"
option = {}

[110]
title = "受到學生愛戴"
text = "你成為了一名受人尊敬的老師，桃李滿天下。"
option = {}

[111]
title = "遭遇挑戰"
text = "你在教學中面臨挑戰，需要展示你的學識和能力。選擇："
option = {137, 138, 139}

[112]
title = "被罷免"
text = "你因政見不同，被罷免回家，但你決定著書立說，名垂後世。"
option = {}

[113]
title = "賺取財富"
text = "你經營的商號賺取了大量財富，決定如何使用這些財富。選擇："
option = {179, 180, 181}

[114]
title = "開設商號"
text = "你決定開設一個商號，開始自己的經商之路。"
option = {}

[115]
title = "成為富商"
text = "你成為了一名富商，擁有了大量的財富和影響力。"
option = {}

[116]
title = "開設分號"
text = "你的商號發展壯大，決定在其他城市開設分號。"
option = {}

[117]
title = "遭遇競爭"
text = "你在商業競爭中遭遇挑戰，需要應對競爭者。選擇："
option = {182, 183, 184}

[118]
title = "發現新商機"
text = "你發現了一個新的商機，決定如何抓住這個機會。選擇："
option = {185, 186, 187}

[119]
title = "被任命為商會會長"
text = "你的商業才華得到認可，被任命為商會會長。"
option = {}

[120]
title = "遭遇挑戰"
text = "你在商會中遭遇挑戰，需要展示你的領導能力。選擇："
option = {188, 189, 190}

[121]
title = "遭遇財務危機"
text = "你的商號遭遇了財務危機，需要迅速應對。選擇："
option = {191, 192, 193}

